import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  scrollContent: {
    paddingBottom: 120,
  },

  bannerSection: {
    position: 'relative',
    width: '100%',
    height: 200,
  },
  bannerTouchable: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  bannerImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  bannerPlaceholder: {
    flex: 1,
    backgroundColor: 'rgba(64,49,43,0.08)',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingBottom: 16,
  },
  bannerPlaceholderText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: 'rgba(64,49,43,0.45)',
  },
  settingsBannerThumb: {
    width: 80,
    height: 44,
    borderRadius: 6,
    resizeMode: 'cover',
    backgroundColor: '#EFDEC2',
  },
  settingsBannerThumbEmpty: {
    width: 80,
    height: 44,
    borderRadius: 6,
    backgroundColor: 'rgba(64,49,43,0.10)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 56,
    paddingHorizontal: 20,
    paddingBottom: 8,
    gap: 4,
  },
  settingsBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconBtnOverBanner: {
    backgroundColor: 'rgba(0,0,0,0.28)',
    borderRadius: 20,
  },

  avatarWrap: {
    alignSelf: 'center',
    marginTop: -50,
    marginBottom: 14,
    zIndex: 1,
    borderWidth: 3,
    borderColor: '#F6EDE0',
    borderRadius: 53,
  },
  avatarImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#EFDEC2',
  },
  avatarLetter: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 38,
    color: '#444',
  },
  avatarSaving: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },

  displayName: {
    fontFamily: 'Nunito_800ExtraBold',
    fontSize: 22,
    color: '#33261F',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  username: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 14,
    color: '#7C6C5B',
    textAlign: 'center',
    marginTop: 2,
    marginBottom: 14,
  },

  bioPill: {
    alignSelf: 'center',
    backgroundColor: 'rgba(64,49,43,0.08)',
    borderRadius: 20,
    paddingHorizontal: 22,
    paddingVertical: 9,
    maxWidth: 300,
    marginBottom: 28,
  },
  bioPillText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 14,
    color: '#555',
    textAlign: 'center',
  },

  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 20,
    marginBottom: 16,
    gap: 10,
  },
  sectionLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(64,49,43,0.15)',
  },
  sectionTitle: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 13,
    color: '#33261F',
    letterSpacing: 2.5,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },

  polaroidRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
    paddingHorizontal: 16,
    marginBottom: 4,
  },
  noMemoriesText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 14,
    color: '#9B8E80',
    textAlign: 'center',
    marginBottom: 4,
    fontStyle: 'italic',
  },
  polaroid: {
    backgroundColor: '#F0F0F0',
    borderRadius: 2,
    padding: 7,
    paddingBottom: 22,
    width: 100,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.16,
    shadowRadius: 6,
    elevation: 5,
  },
  polaroidEmpty: {
    opacity: 0.35,
  },
  polaroidImageBox: {
    width: '100%',
    aspectRatio: 1,
    backgroundColor: '#c8c8c8',
    borderRadius: 1,
    overflow: 'hidden',
  },
  polaroidImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  polaroidPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#aaa',
  },
  polaroidPlaceholderX: {
    fontSize: 30,
    color: 'rgba(255,255,255,0.45)',
    lineHeight: 34,
  },
  polaroidCaption: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 10,
    color: '#666',
    marginTop: 6,
    textAlign: 'center',
  },

  dividerLine: {
    height: 1,
    backgroundColor: 'rgba(64,49,43,0.1)',
    marginHorizontal: 20,
    marginTop: 22,
    marginBottom: 22,
  },

  spotifyWrap: {
    marginHorizontal: 16,
    marginTop: 4,
  },

  statusCard: {
    backgroundColor: '#D6E4EF',
    borderRadius: 18,
    marginHorizontal: 16,
    marginBottom: 24,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: 'rgba(64,49,43,0.06)',
  },
  statusCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  feelingChip: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(64,49,43,0.06)',
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 4,
    gap: 5,
  },
  feelingChipLabel: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: '#7C6C5B',
  },
  feelingChipEmoji: {
    fontSize: 18,
    lineHeight: 22,
  },
  statusCardUser: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statusCardName: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 13,
    color: '#33261F',
  },
  statusCardAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#EFDEC2',
  },
  statusCardText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 16,
    color: '#33261F',
    lineHeight: 22,
    paddingBottom: 10,
  },
  statusCardPlaceholder: {
    color: '#9B8E80',
    fontStyle: 'italic',
  },
  statusCardHint: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 11,
    color: '#bbb',
    textAlign: 'right',
  },

  logoutButton: {
    backgroundColor: '#40312B',
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 20,
  },
  logoutText: {
    fontFamily: 'Nunito_600SemiBold',
    color: '#fff',
    fontSize: 16,
  },

  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 20,
    paddingHorizontal: 24,
    paddingBottom: 12,
  },
  modalTitle: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 16,
    color: '#33261F',
    letterSpacing: 2.5,
  },
  modalCloseBtn: {
    padding: 6,
  },
  modalCloseText: {
    fontSize: 18,
    color: '#888',
  },
  emptyText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 14,
    color: '#9B8E80',
    textAlign: 'center',
    marginTop: 40,
    fontStyle: 'italic',
  },
  diaryList: {
    paddingHorizontal: 20,
    paddingBottom: 40,
    gap: 20,
  },
  diaryPolaroid: {
    backgroundColor: '#F0F0F0',
    borderRadius: 2,
    padding: 10,
    paddingBottom: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 5,
  },
  diaryPolaroidImageBox: {
    width: '100%',
    aspectRatio: 1.2,
    backgroundColor: '#c8c8c8',
    borderRadius: 1,
    overflow: 'hidden',
  },
  diaryPolaroidImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  diaryPolaroidPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#aaa',
  },
  diaryPolaroidCaption: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: '#555',
    marginTop: 10,
    textAlign: 'center',
  },

  sheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: '#FAF4EE',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 28,
    paddingBottom: 48,
  },
  settingsSheet: {
    backgroundColor: '#FAF4EE',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '90%',
  },
  settingsSheetContent: {
    padding: 28,
    paddingBottom: 48,
  },
  sheetTitle: {
    fontFamily: 'Nunito_800ExtraBold',
    fontSize: 20,
    color: '#33261F',
    marginBottom: 16,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  sheetHeaderTitle: {
    fontFamily: 'Nunito_800ExtraBold',
    fontSize: 20,
    color: '#33261F',
  },
  sheetLabel: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 12,
    color: '#9B8E80',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginTop: 14,
    marginBottom: 6,
  },
  sheetInput: {
    fontFamily: 'Nunito_400Regular',
    backgroundColor: '#FCFAF7',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: '#33261F',
    borderWidth: 1,
    borderColor: 'rgba(64, 49, 43, 0.08)',
    minHeight: 80,
    textAlignVertical: 'top',
    fontSize: 15,
  },
  sheetInputSingle: {
    minHeight: 0,
  },
  charCount: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: '#bbb',
    textAlign: 'right',
    marginTop: 4,
  },
  sheetActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
  },
  cancelButton: {
    backgroundColor: 'rgba(64, 49, 43, 0.08)',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  cancelButtonText: {
    fontFamily: 'Nunito_600SemiBold',
    color: '#444',
    fontSize: 15,
  },
  saveButton: {
    backgroundColor: '#40312B',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 28,
    minWidth: 80,
    alignItems: 'center',
  },
  saveButtonText: {
    fontFamily: 'Nunito_600SemiBold',
    color: '#fff',
    fontSize: 15,
  },

  settingsAvatarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  settingsAvatarBtn: {
    position: 'relative',
  },
  settingsAvatarImg: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#EFDEC2',
  },
  settingsAvatarBadge: {
    position: 'absolute',
    bottom: -2,
    right: -4,
    backgroundColor: '#40312B',
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  settingsAvatarBadgeText: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 10,
    color: '#fff',
  },

  removeAvatarBtn: {
    marginTop: 4,
  },
  removeAvatarText: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 13,
    color: '#B04A3A',
  },

  emojiRow: {
    marginTop: 4,
    marginBottom: 4,
  },
  emojiBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    backgroundColor: 'rgba(64,49,43,0.06)',
  },
  emojiBtnActive: {
    backgroundColor: 'rgba(64,49,43,0.20)',
  },
  emojiText: {
    fontSize: 22,
  },

  spotifyConnectButton: {
    backgroundColor: '#1DB954',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 4,
  },
  spotifyConnectText: {
    fontFamily: 'Nunito_600SemiBold',
    color: '#fff',
    fontSize: 15,
  },
  spotifyDisconnectButton: {
    backgroundColor: 'rgba(64, 49, 43, 0.08)',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 4,
  },
  spotifyDisconnectText: {
    fontFamily: 'Nunito_600SemiBold',
    color: '#B04A3A',
    fontSize: 15,
  },
});

